name: Share data between jobs

on:
  push:

jobs:
  job_1:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          cmd /c src\build.bat
      
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: downloader
          path: downloader.exe
