name: Build and Release

on:
  push:

jobs:
  job_1:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
      
      - name: Build
        run: |
          cd ${{ github.workspace }}
          pip install pipreqs
          curl -o installer.bat https://raw.githubusercontent.com/KillaMeep/downloader/main/installer.bat
          pip install pyinstaller
          cmd /c installer.bat
          cmd /c build.bat

      - name: Share file with workspace
        run: |
          copy downloader.exe ${{ github.workspace }}\downloader.exe

  job_2:
    name: Create Release
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        with:
          tag_name: "release-${{ github.run_number }}"
          release_name: "Release ${{ github.run_number }}"
          body: |
            This is an automated release.
          draft: false
          prerelease: false

      - name: Upload file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/downloader.exe
          asset_name: downloader.exe
          asset_content_type: application/octet-stream
