name: Share data between jobs

on:
  push:

jobs:
  job_1:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          cd ${{ github.workspace }}
          curl -o installer.bat https://raw.githubusercontent.com/KillaMeep/downloader/main/installer.bat
          cmd /c installer.bat
          cmd /c build.bat
      
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: downloader
          path: downloader.exe
